### ISSUE TITLE
How to enable smartdevicelink.service?

### ISSUE THREAD

**Issue by propella** [phongt/meta-sdl#2]
Hello,

I assume this recipe would `start smartdevicelink.service` automatically by `SYSTEMD_AUTO_ENABLE = "1"`.
But for some reason, it didn't start when I include it AGL, so I needed to make a symlink manually in `do_install_append`.

    install -d ${D}/${systemd_unitdir}/system/multi-user.target.wants
    ln -fs ../smartdevicelink.service ${D}${systemd_unitdir}/system/multi-user.target.wants/smartdevicelink.service

I don't know how SYSTEMD_AUTO_ENABLE suppose to work, but is making symlink necessary? If so, I'd like to send the PR.

**Comment by phongt** [comment]
@propella 
Thank for your information. I have just checked. The correct value of SYSTEMD_AUTO_ENABLE should be "enable" not "1".  something was wrong in the recipe.  SYSTEMD_AUTO_ENABLE is set "enable" in default in [systemd.bbclass](https://git.yoctoproject.org/cgit.cgi/poky/plain/meta/classes/systemd.bbclass). I think, the variable is not necessary here. Please remove it in sdl-core_4.1.0.bb

I have just pushed the change to branch [fix_systemd_startup_issue](https://github.com/phongt/meta-sdl/tree/fix_systemd_startup_issue). Could you try this?

Please let me know there is other problem. Thank you.

**Comment by propella** [comment]
It works!
I confirmed fix_systemd_startup_issue branch enables the service.
Thank you for the quick action, @phongt !
