### ISSUE TITLE
OpenEmbedded Layer Index issuing warnings for SDL layer

### ISSUE THREAD

**Issue by jeremiah** [phongt/meta-sdl#3]
You can see the warning here: https://layers.openembedded.org/layerindex/branch/master/layer/meta-sdl/

Look like all we need is to bring back the master branch and that will go away. :-)

**Comment by phongt** [comment]
@jeremiah  Thanks, I will check.

**Comment by phongt** [comment]
Add [master](https://github.com/phongt/meta-sdl/tree/master) branch and update README.
