### ISSUE TITLE
Plans for supporting 4.5.x?

### ISSUE THREAD

**Issue by matthoosier** [phongt/meta-sdl#8]
Hi; I was just wondering whether you have any plans to publish a branch that builds upstream version 4.5.x.

If not, I could contribute something.

**Comment by phongt** [comment]
I am working for 4.5.1 sdl-core recipe and checking many issues currently.

- https://github.com/smartdevicelink/sdl_core/issues/2137. 

- support boost 1.66 in recipes.

I will not be available in next couple of weeks. Maybe I will back in Mid-May with this.

**Comment by phongt** [comment]
> - support boost 1.66 in recipes.

[boost: update to 1.66.0](https://git.yoctoproject.org/cgit.cgi/poky/commit/meta/recipes-support/boost?id=b112b094cce627d024df5131a4533ca5f84e5443) in poky master branch and sumo branch now.

**Comment by phongt** [comment]
@matthoosier 
support for 4.5.1 with poky sumo branch.
please check branch [release/4.5.x](https://github.com/phongt/meta-sdl/tree/release/4.5.x)
