### ISSUE TITLE
Reason for suppression of PARALLEL_MAKE?

### ISSUE THREAD

**Issue by matthoosier** [phongt/meta-sdl#9]
Is there any known problem that caused you to enforce a serial build by setting PARALLEL_MAKE empty?

I typically have  no trouble doing parallel builds ("make -j8" or similar) when working directly with upstream, and I don't find any issues when I allow the Bitbake builds of sdl-core to run in parallel.

**Comment by phongt** [comment]
As my remember, there is a error of dependency which made error of sdl-core building in  v4.1.0. I have not checked with the latest sdl-core version. Which sdl-core version did you tested?

**Comment by matthoosier** [comment]
I've been working with 4.4.1.
